import os

#This script is used to zero index the png's which were generated by ffmpeg

numbers = ["00", "01", "02", "03", "04", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18"]

for i in numbers:


    folder = r'C:/Users/alex_/Desktop/Skole/VisuellIntelligens/miniProject/processed_to_images/Video000' + i + r'_Ano/data/'
    count = 0

    for file_name in os.listdir(folder):
        source = folder + file_name
        if count < 10:
            number = "00000"+str(count)
        elif count > 9 and count < 100:
            number = "0000"+str(count)
        else:
            number = "000"+str(count)
        
        destination = folder + "frame_" + number + ".PNG"

        os.rename(source, destination)
        count += 1